#!/usr/bin/env bash
# CONCURRENT-FILL launch (project.tape d_parallel_fire) — generated by dft_fill_plan_disk.
# physcores=64 n_decks=3 ranks_per_deck=16 core_slots=4 disk_slots=20 concurrent=3 sum_np=48
set -uo pipefail
cd "$(dirname "$0")"

# 한 deck = 한 ph.x job. 동시 job 수 ≤ SLOTS(core ∧ disk), Σ(-np) ≤ PHYSCORES.
PHYSCORES=64
RANKS_PER_DECK=16
CORE_SLOTS=4
DISK_SLOTS=20
SLOTS=4
FREE_DISK_GB=300
SCRATCH_GB_PER_JOB=15
WALLTIME_H=20
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

# DECKS = 발사할 deck 디렉터리들. 디스패처가 실제 목록으로 치환한다.
DECKS=( "$@" )
[ "${#DECKS[@]}" -eq 0 ] && DECKS=( */ )

declare -a PIDS=()
running=0
for d in "${DECKS[@]}"; do
  d="${d%/}"
  [ -f "$d/ph.in" ] || { echo "skip $d (no ph.in)"; continue; }
  # 슬롯이 다 차 있으면 한 job 이 끝날 때까지만 기다린다(rolling fill, 전면 wait 아님).
  if [ "$running" -ge "$SLOTS" ]; then
    wait -n
    running=$((running-1))
  fi
  ( cd "$d" && setsid timeout "${WALLTIME_H}h" \
      mpirun --allow-run-as-root -np "$RANKS_PER_DECK" --bind-to none \
      ph.x -in ph.in > ph.out 2>&1 ) &
  PIDS+=( $! )
  running=$((running+1))
  echo "launched $d pid=$! (-np $RANKS_PER_DECK, slot $running/$SLOTS)"
done

# 남은 모든 background job 수확.
rc=0
for p in "${PIDS[@]}"; do wait "$p" || rc=1; done
echo "FILL DONE (rc=$rc)"
exit $rc
